server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 111.229.5.238
aliyun:
  sms:
    accessKeyId: LTAI4FbhPQRixnqyTpn7RxLb
    accessKeySecret: RbKCVVgew2mHCFrckHYvb7ULmJzZgw
    template_code: SMS_181201808
    sign_name: 十次方APP